name: hyperpay
description: A plugin to wrap HyperPay mobile SDK for iOS and Android, used to accept payments in Flutter apps using HyperPay Payments Gateway.
version: 1.0.0-dev.7
repository: https://github.com/nyartech/hyperpay

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nyartech.hyperpay
        pluginClass: HyperpayPlugin
      ios:
        pluginClass: HyperpayPlugin
